version: "3.9"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hb_app
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: hb_nginx
    ports:
      - "8078:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:16
    container_name: hb_db
    environment:
      POSTGRES_DB: home_budget
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5438:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  node:
    image: node:20-alpine
    container_name: hb_node
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
    ports:
      - "5176:5173"

volumes:
  db_data:
